# Generated by Django 4.2 on 2025-08-28 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='college_id',
            new_name='employee_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
