# Generated by Django 4.2 on 2025-08-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_college_id_employee_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user_id',
        ),
    ]
