# Generated by Django 4.2 on 2025-08-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='employee_id',
            new_name='admin_id',
        ),
    ]
